//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public long id { get; set; }
        public string Company_name { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
