//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long order_id { get; set; }
        public Nullable<long> customer_id { get; set; }
        public string order_name { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
